# 池化层

池化层能够降低卷积层对位置的敏感性, 不改变通道数的同时可以降低输入的维度

In [1]:
import torch
from torch import nn
import d2l.torch as d2l

最大池化层 : 输出窗口中的最大值

平均池化层 : 输出窗口中的平均值

In [2]:
def pool2d(X, pool_size, mode='max'):
    ph, pw = pool_size
    Y = torch.zeros((X.shape[0]-ph+1), X.shape[1]-pw+1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i+ph, j:j+pw].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i+ph, j:j+pw].mean()
    return Y

验证

In [3]:
X = torch.tensor([[0.0, 1.0, 2.0],
                  [3.0, 4.0, 5.0],
                  [6.0, 7.0, 8.0]])
print(pool2d(X, (2, 2), 'max'))
print(pool2d(X, (2, 2), 'avg'))

tensor([[4., 5.],
        [7., 8.]])
tensor([[2., 3.],
        [5., 6.]])


填充和步幅

在默认情况下, 深度学习框架中的步幅和池化层的窗口大小相同, 也就是说池化层的 $kernel\_size$ 不会在池化的过程中相同

In [4]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
pool2d = nn.MaxPool2d(kernel_size=3, padding=1, stride=2)
print(X)
pool2d(X)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])


tensor([[[[ 5.,  7.],
          [13., 15.]]]])

通道数不变

In [5]:
X = torch.cat((X, X+1), 1)
print(X)
net = nn.MaxPool2d(kernel_size=3, padding=1, stride=2)
print(net(X))

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])
tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])
