# 转置卷积

In [1]:
import torch
import torchvision
from torch import nn
import d2l.torch as d2l

![transpose](https://zh-v2.d2l.ai/_images/trans_conv.svg)

In [2]:
def trans_conv(X, k):
    h, w = k.shape
    Y = torch.zeros((X.shape[0] + h - 1, X.shape[1] + w - 1))
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            Y[i:i+h, j:j+w] += X[i, j] * k
    return Y

In [3]:
X = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])

In [4]:
trans_conv(X, K)

tensor([[ 0.,  0.,  1.],
        [ 0.,  4.,  6.],
        [ 4., 12.,  9.]])

使用高级 $API$

In [6]:
tconv = nn.ConvTranspose2d(1, 1, kernel_size=2, bias=False)
tconv.weight.data = K.reshape(1, 1, 2, 2)
tconv(X.reshape(1, 1, 2, 2))

tensor([[[[ 0.,  0.,  1.],
          [ 0.,  4.,  6.],
          [ 4., 12.,  9.]]]], grad_fn=<ConvolutionBackward0>)

设置 stride

![stride](https://zh-v2.d2l.ai/_images/trans_conv_stride2.svg)

In [8]:
tconv = nn.ConvTranspose2d(1, 1, kernel_size=2, stride=2, bias=False)
tconv.weight.data = K.reshape(1, 1, 2, 2)
tconv(X.reshape(1, 1, 2, 2))

tensor([[[[0., 0., 0., 1.],
          [0., 0., 2., 3.],
          [0., 2., 0., 3.],
          [4., 6., 6., 9.]]]], grad_fn=<ConvolutionBackward0>)

如果有多个通道, 那么就会每个通道分配一个卷积核张量